server.port: 8080
server.error.include-message: ALWAYS


info:
  app:
    name: "java-sat-recruitment"
    description: "This is a simple API to create users"
    version: 1.0
users:
    normal:
        gift:
            min: 0.12
            max: 0.8
    super:
        gift:
            min: 0
            max: 0.2
    premium:
        gift:
            min: 0
            max: 1